### PR TITLE
[WIP] add Postman collection with some examples of VueSF API requests

### PR DESCRIPTION
**Pull request by janmyszkier**
the general idea behind this PR is to provide a PR that:
- provide sample requests for all API endpoints with as little configuration as possible (will allow us to remove example requests from API MD doc later because using postman is easier)
- provide sample tests within the postman collection to deprecate https://github.com/DivanteLtd/vue-storefront-simple-api by reporting what data is still missing in the response

### CODE REVIEW

**Comment by pkarw** [comment]
Looks nice! is it ready to be merged in?

**Comment by janmyszkier** [comment]
@pkarw I didn't test user endpoints at all yet(not scope of my work), but the other ones are currently used by me in the development and definitely work.

**Comment by lsimone** [comment]
Nice idea.
Wouldn't it be nice to have also a swagger in order to provide documentation instead of just examples?

**Comment by janmyszkier** [comment]
@lsimone "being nice" is not a good reason for investing manhours into a feature. What VALUE does adding swagger bring over what we currently have?

**Comment by lsimone** [comment]
@janmyszkier ok, so here just my 2 cents: 
`some examples` are not comprehensive documentation about an interface, while swagger is.
I think examples are useful, but if you really want to define a specification, you would need something more solid, and IMHO, having a documented interface (for any tool) **is a value**

**Pull request closed without merging**
